### ISSUE TITLE
grammar does not seems to work

### ISSUE THREAD

**Issue by xujli** [outlines-dev/outlines#1006]
### Describe the issue as clearly as possible:

I used the code in [https://outlines-dev.github.io/outlines/reference/json_mode/](url). Pretrained mistral-7b-v0.2 with a custom file path is used as the model. 

However, the result is **'\n\n 1. \t' with endless '\t'.** 
While pydantic model json schema and regex work fine, json schema with json schema only generates '{}'. 
https://outlines-dev.github.io/outlines/reference/json/
There seems no similar bug reported in outlines==0.0.46, I prefer to wonder if there are some deployment mistakes in my environment. I double-checked this question with gpt2.

Please give me some suggestions to solve this question. I am looking forward to hearing back from you soon.

### Steps/code to reproduce the bug:

```python
def main():
    import outlines
    from outlines import models, generate

    json_grammar = outlines.grammars.json
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = models.transformers("./models/mistral-7b", device=device)
    generator = generate.cfg(model, json_grammar)
    sequence = generator("Generate valid JSON", max_tokens=50)
    print(sequence)

main()
```

### Expected result:

```shell
A valid json string.
```

### Outlines/Python version information:

python 3.9.13
interegular: 0.3.3
jinja2: 3.1.3
lark: 1.1.9
nest_asyncio: 1.6.0
numpy: 1.23.4
cloudpickle: 3.0.0
diskcache: 5.6.3
pydantic: 2.7.4
numba: 0.59.1
referencing: 0.33.0
jsonschema: 4.22.0
requests: 2.31.0
tqdm: 4.65.0
datasets: 2.18.0
typing_extensions: 4.9.0
pycountry: 24.6.1
pyairports: 2.1.1
outlines==0.0.46

**Comment by lapp0** [comment]
CFG is still a work in progress. Hoping to have it in a great working state in a few weeks.

Could you try using an unconstrained schema for now?

`generator = outlines.generate.json(model, "{}")`

(One more thing, if you use `max_tokens` it may truncate the output before valid json is finished)

**Comment by xujli** [comment]
Thanks for your kind reply. Unfortunately, unconstrained schema only generates '-1'.
`
generator = outlines.generate.json(model, "{}")
`
I am glad to witness the progress of CFG, waiting for your success! 
I'll close this issue.

**Comment by lapp0** [comment]
`-1` is valid json. If you want an object you could try 

`outlines.generate.json(model, '{"type": "object"}')`

```
>>> generator = outlines.generate.json(model, '{"type": "object"}')
Compiling FSM index for all state transitions: 100%|___________________________________________________________________________________________________________________________| 243/243 [00:01<00:00, 138.58it/s]
>>> generator("Generate valid JSON: ", max_tokens=50)
{'name': 'Alice', 'age': 25, 'address': {'city': 'San Francisco', 'state': 'CA', 'zip': 12345}}
```

Please subscribe to this issue if you want to track CFG progress https://github.com/outlines-dev/outlines/issues/959
