### ISSUE TITLE
Modality heads in multi modal generation 

### ISSUE THREAD

**Issue by JulesGM** [outlines-dev/outlines#1020]
In multimodal models, if you want an image in a text, a common thing is to have an embedding from that modality projected into the embedding space of the embedding layer of the transformer, & that embedding be put in the sequence along the text embeddings (the output of the torch.nn.Embedding layer), & then passed to the rest of the transformer (a position embedding would also be added to that modality embedding). 

One can also generate in a multi modal way by putting a different head over the final embedding layer, & feeding that to a separate generation model.

Being able to support such a thing for generation in outlines would be great. One way that I could see it work is, when defining a regex or a cfg, have the ability to specify a special token like `<image_head>` in the schema / grammar, and when you get to that place in the schema / grammar, you instead use the head to generate that modality. I could see having multiple heads & multiple special tokens, one for each modality. 

I can also see this be a type in json schemas. The JSON scenario is the one I'm the most interested / serious about right now.

If this doesn't already exist, I would be serious on at least starting the work on getting it done (I want to get it to work for json schemas), so indications on how to do it would correctly and cleanly would be nice & really helpful. @rlouf bonjour.

**Comment by lapp0** [comment]
I'm **very** interested in this idea. Is there a standard in HuggingFace Transformers which specifies that a token should result in generation of an embedding from a non-LM head? I've actually looked for this previously and I've only found the opposite - using a token which signifies an embedding **input** (e.g. the `<image>` token in Llava models).

Could you link some resources?

**Comment by JulesGM** [comment]
I made it up, but it seems to me like a fairly obvious way to go about it, a bit like being the other side of the LLaVa coin, & assumed people would have done that already. If that hasn't been done, we should publish it.

**Comment by lapp0** [comment]
This seems out of scope for Outlines unless / until there is a model which generates tokens that signify a separate non-LM head should be used to generate an embedding.

Please reach out to me preferably by Discord (`andrewlapp`) or alternatively by email (`andrew@gh1a43.rew.la`) if you'd like to exchange ideas on this and potentially collaborate on creating this!

**Comment by lapp0** [comment]
@JulesGM you might be interested in reaching out to this user working on a similar project in the Outlines discord

![image](https://github.com/user-attachments/assets/a9c3ef41-ccce-4812-85bf-7a061b95500c)

**Comment by JulesGM** [comment]
awesome!
