### ISSUE TITLE
Need accelerate to use CUDA (even though accelerate is installed)

### ISSUE THREAD

**Issue by CakeCrusher** [outlines-dev/outlines#1031]
### Describe the issue as clearly as possible:

Cannot set device due to missing accelerate error even though accelerate is installed

### Steps/code to reproduce the bug:

```python
https://colab.research.google.com/drive/1fxUkcPXJXFVUeOomz_LKPC9CkfGQ1o4g?usp=sharing
```

### Expected result:

```shell
shouldnt complain about accelerate dependency and should proceed to use GPU for inference.
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by lapp0** [comment]
This appears to be an issue involving using `accelerate` with Colab. Could you try this solution and report back whether it works? https://stackoverflow.com/a/76902764

**Comment by lapp0** [comment]
Please re-open this issue if the reproduction steps don't work and you determine that the issue is with Outlines specifically.
