### ISSUE TITLE
Mamba documentation broken display

### ISSUE THREAD

**Issue by doza210** [outlines-dev/outlines#1071]
### Describe the issue as clearly as possible:

The documentation page of Mamba is not displaying correctly. It is showing extra large icons and basic text, so there must be something wrong with the markdown file.

link: https://outlines-dev.github.io/outlines/reference/models/mamba.md

### Steps/code to reproduce the bug:

```python
1) Go to https://outlines-dev.github.io/outlines/reference/models/mlxlm/
```

### Expected result:

```shell
Mamba documentation page
```

### Outlines/Python version information:

n/a

**Comment by rlouf** [comment]
Thank you for opening an issue! This is because the file was recently removed but the navigation was not updated. This is being fixed in #1072.
