### ISSUE TITLE
Add support for Google Vertex AI models (Bison and Gecko)

### ISSUE THREAD

**Issue by harshkumarchourasia** [outlines-dev/outlines#142]
Google has recently introduced a new machine learning platform called Vertex AI, which includes several interesting models such as Bison and Gecko ([learn more here](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/models)). These models have potential for further expanding the capabilities of the 'outlines' project.

I propose updating the 'outlines' project to incorporate Google's Vertex AI models (Bison and Gecko) into the toolset, allowing users to leverage the power of these cutting-edge generative AI models.

I would be happy to contribute by submitting a pull request to implement this feature. Do let me know if this has community and maintainer support, and any additional requirements or suggestions for implementing this update.

Looking forward to the community's feedback and collaborating on this exciting enhancement!

**Comment by dan-zheng** [comment]
I would be interested in support for Google Vertex AI models!

**Comment by rlouf** [comment]
We can support these models in the same way we support OpenAI models. However, from what I see in the documentation unlike OpenAI it is not possible to send a token mask over via the API, which means that the constrained generation features won't be available. They would therefore only be usable for simple completion.
