### ISSUE TITLE
Bug in retrying mechanism

### ISSUE THREAD

**Issue by arunpatro** [outlines-dev/outlines#181]
I frequently run into `RateLimitError` -> `FileNotFoundError`, while calling openai models with high batchsize. I think this occurs because of the incorrect order of decorators [here](https://github.com/normal-computing/outlines/blob/main/outlines/models/openai.py#L364-L366). 

I tried to reorder them, but I ran into other weird errors. I feel `cache` decorator receives a `RateLimitError` and cannot understand it, therefore throws a `FileNotFoundError` which is not captured in the above call stack. 

Looks like percache cannot cache a callable type.

**Comment by rlouf** [comment]
Thanks for reporting. Do you want to take a shot at fixing this?

**Comment by arunpatro** [comment]
Sure, I kinda already tried a bunch of tricks but wasn't able to. I will spend some time again.

**Comment by rlouf** [comment]
This may be fixed by #361
