### ISSUE TITLE
Consider using `safetensors` to load weights in memory

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#189]
The [safetensors](https://huggingface.co/docs/safetensors/speed) library can to load weights faster on device using cudaMemCpy directly. We should consider it for loading `transformers` models in Outlines.

**Comment by arunpatro** [comment]
Its hard to say if a model has weights in safetensors format in huggingface hub. I couldn't find any config. The user can always pass `use_safetensors=True` as model_kwargs.
