### ISSUE TITLE
Something weird with the setup script

### ISSUE THREAD

**Issue by havietisov** [outlines-dev/outlines#209]
Tried installing from source, got this : 
`Installing collected packages: UNKNOWN
  Running setup.py develop for UNKNOWN
Successfully installed UNKNOWN-0.1.dev188+gde8c2e5`
This probably should be fixed somehow

**Comment by rlouf** [comment]
What command did you run?

**Comment by havietisov** [comment]
tried `pip install -e .[test]` and just `pip install .`
same result

**Comment by rlouf** [comment]
I cannot reproduce it locally. Did you try with a fresh virtual environment?

**Comment by havietisov** [comment]
Tried to do it with just vanilla python virtual environment

**Comment by rlouf** [comment]
Can you retry with the attempted fix in #242?

**Comment by havietisov** [comment]
doesn't work. here's my loggg : 
```
/mnt/j/outlines$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /mnt/j/outlines
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.1.dev199+g91f95d8-py3-none-any.whl size=5279 sha256=6af174ca690c71f7e2b8d2f2d7f4ec4b32017c7ab34253a41c0577a08b936c9e
  Stored in directory: /tmp/pip-ephem-wheel-cache-5yvxrire/wheels/e4/74/f6/9029229c3790401793af028cdcb4de8015ab9d87070e119f54
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.1.dev199+g91f95d8
```

**Comment by havietisov** [comment]
Well, this time I just tried to install it using PIP. 
tried to upgrade setuptools to 68.1.2, same error
python version is 3.10.6-1~22.04

I noticed that there's no setupscript in the repository. 
When I made a setupscript on my own, package is finally installing like it should. 
Maybe, this can be remedied by just adding a setupscript?

**Comment by havietisov** [comment]
Ok, anyway, would it be OK if I just add a setupscript?
