### ISSUE TITLE
Docs appear to be out of date

### ISSUE THREAD

**Issue by jlaneve** [outlines-dev/outlines#217]
Looking at the [controlled generation docs](https://normal-computing.github.io/outlines/reference/controlled_generation.html#the-future-of-constrained-generation) docs, it mentions that outlines doesn't support JSON constraining. However, the README gives an example that appears functional - are the docs out of date here?

<img width="842" alt="Screen Shot 2023-08-14 at 4 00 32 PM" src="https://github.com/normal-computing/outlines/assets/5252587/ab2ee59f-ba32-4b82-b9d9-301beeb49f48">

**Comment by rlouf** [comment]
Docs are out of date indeed, the README should be up to date. We're always looking for people to help us!
