### ISSUE TITLE
Non-seeded generations by default?

### ISSUE THREAD

**Issue by mondaychen** [outlines-dev/outlines#221]
Currently the generation is seeded by default.
I can get the exact same output when running the json example on README
```
{
  "name": "ranbelt",
  "age": 26,
  "armor": "chainmail",
  "weapon": "bow",
  "strength": 5
}
```

Not sure if this is the best default behavior. Users might expect LLMs to generate various of outputs.

**Comment by rlouf** [comment]
Feel free to open a PR, shouldn't be difficult to change.
