### ISSUE TITLE
Support output probabilities when using regex

### ISSUE THREAD

**Issue by thomasahle** [outlines-dev/outlines#262]
When generating with a regular expression, like this:
```
model = ziplm(training=open('mobydick.txt').read().lower())
prompt = "Ahab is seeking vengeance against"
regex_str = "(ishmael|moby dick)"
sequence = generate.regex(model,regex_str, max_tokens=10)(prompt)
```
It would be useful to not just get the string "ishmael" or "moby dick", but the probabilities of generating each one.

Of course I could just do 1000 generations, black box with different seeds, and count the outcomes, but that seems a lot slower than just getting the probabilities from the model.

Another approach would be for me to generate all the strings that match the regex, manually, and then compute the logprobs of each. But that doesn't work for some regexes like (\d+), which can match infinitely many different strings.

Ideally a solution would walk the NFA of the regex and efficiently add up the relevant logprobs.

**Comment by brandonwillard** [comment]
For anyone interested, probabilities can be gathered during generation by way of a custom sampler function.  See [here](https://gist.github.com/brandonwillard/e1f41053c599bb584d4b922251cd96f5) for an example.

**Comment by thomasahle** [comment]
Does that sum the probabilities of all the paths that would lead to the output string? (Like you'd get if you used infinite repeated sampling.) Or just the probability of the path the generator actually chooses?
