### ISSUE TITLE
Reproducible bug

### ISSUE THREAD

**Issue by AICat7000** [outlines-dev/outlines#263]
In the file test_regex.py, if you change the line 

vocabulary = {"<EOS>": 0, "-": 1, "1": 2, "0.": 3, "431": 4, "a": 5, "A": 6}

into the following 

vocabulary = {"-": 1, "1": 2, "0.": 3, "431": 4, "a": 5, "<EOS>": 0, "A": 6}

This gives the following error: ValueError: not enough values to unpack (expected 1, got 0) in the create proposal create_proposal function.

I found this because I was trying to use the library with another tokenizer. Not sure if it is related, but if I create a python script with the following 2 lines of code:

import interegular
print (interegular.parse_pattern("(1|431a|431A-)").to_fsm().reduce())

I get different outputs every time I run it.

Any help would be really appreciated

**Comment by brandonwillard** [comment]
It sounds like you're noticing that `interegular` does not provide deterministic state ordering/labeling.  We have a work-around for this in #272, but that doesn't appear to indicate a bug in `test_regex.py`.  On a related note, one of our tests in `test_parsing.py` is flaky for this reason and the work-around will fix that issue.

Regardless, thanks for creating an issue.  I'm going to close this for now, but feel free to update this if we missed anything.
