### ISSUE TITLE
Feature request: GGML/GGUF support 

### ISSUE THREAD

**Issue by jccalvojackson** [outlines-dev/outlines#270]
GGML/GGUF model versions are significantly faster and lighter compared to their equivalent pytorch-format models.
It would be great to add to the documentation how to interface with these models (not sure how to go about it).
I imagine this could be possible without necessarily writing the cpp version of this library.

**Comment by Ozennefr** [comment]
FYI, ctransformers have an issue discussing outlines integration:
https://github.com/marella/ctransformers/issues/91

Not 100% sure it works as expected

**Comment by 903124** [comment]
I've tried it works on `outlines==0.0.7` but broken on 0.0.8

**Comment by Ozennefr** [comment]
Works for me on outlines==0.0.8 🤨
If you’re generating json schema with string attributes, I advise using ‘consrt’ from pydantic instead of ‘str’ with a regex constraint to avoid generating double quotes or other characters that would break the json.

**Comment by rlouf** [comment]
We solved this problem recently, but haven't cut a new release since 😬 Did you try with the latest commit?

Will cut a release soon!

**Comment by Ozennefr** [comment]
For outlines 0.0.9, the forward pass should return a `CausalLMOutputWithPast` object instead of a `CausalLMOutput`. A drop in replacement work although more tweaks should allow for significant speedups.

**Comment by rlouf** [comment]
Would you be willing to open a PR?

**Comment by Ozennefr** [comment]
Not sure how to proceed / where to implement but I can give it a go.
