### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by francescocassini** [outlines-dev/outlines#284]
I am having a lot of trouble installing this library.
At first I ran pip install outlines on an enviroment with python==3.11, but every time I tried to run any of the examples I always get this error "beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation)."

Then I restarted by creating clean conda enviroments (one time with python 3.10 and another with 3.11) and running only "pip install outlines," but it still gives me the same error.
I finally downloaded the code from github and ran the enviroment creation via "conda env create -f environment.yml," but at the end I get an "× Getting requirements to build editable did not run successfully.│ exit code: 1."
I can't figure out what I'm doing wrong.  I am working on Ubuntu 22.04 with conda last release and pip=23.2.1

Can someone help me to understand?
Thanks in advance

**Comment by rlouf** [comment]
This looks like a problem with `pytorch`. Can you try installing PyTorch only in a clean conda environment?

**Comment by brandonwillard** [comment]
This is a `pytorch` issue stemming from the latest `beartype` version.  If you set `beartype` back a minor version it should work.

**Comment by francescocassini** [comment]
Exactly, it is a problem related to beartype: I installed version 0.15 and everything worked perfectly!
Thanks to both of you, I look forward to developing with outlines.
thanks again
