### ISSUE TITLE
`transformers.device = None` default sneakily overwrites `device_map='auto'`

### ISSUE THREAD

**Issue by freckletonj** [outlines-dev/outlines#299]
I was trying to allow `accelerate` to load straight to GPU, and use multiple GPUs by passing `device_map='auto'`. But alas, the following line of code overrides it.

https://github.com/outlines-dev/outlines/blob/cae6a534f7b4aa8ea9b64aae2bd9f4335a5f24fc/outlines/models/transformers.py#L139

Now I have this, which is bad because `device='auto'` is an unconventional usage of `device`, which typically refers to `cpu/cuda:0` etc.

```python
    model = models.transformers(
        model_path,
        model_kwargs=dict(
            trust_remote_code=True,
            local_files_only=True,
            device_map='auto',
        ),
        device='auto',
    )
```

The above code saves me :+1:

**Comment by brandonwillard** [comment]
Agh; OK, I'll take a crack at it tonight.
