### ISSUE TITLE
JSON schema used in generation should not require optional annotations

### ISSUE THREAD

**Issue by mattkindy** [outlines-dev/outlines#309]
In [outlines/text/json_schema.py#expand_json_schema](https://github.com/outlines-dev/outlines/blob/main/outlines/text/json_schema.py#L95), part of the regex generation process attempts to grab the `title` property from the current schema/sub-schema whenever it encounters a schema with `properties`:

https://github.com/outlines-dev/outlines/blob/5af26cb93905605451ffe3a2594a7c60316a7505/outlines/text/json_schema.py#L136

However, [the current JSON schema reference](https://json-schema.org/understanding-json-schema/reference/annotations#annotations) notes:

> JSON Schema includes a few keywords, that aren't strictly used for validation, but are used to describe parts of a schema. None of these "annotation" keywords are required, but they are encouraged for good practice, and can make your schema "self-documenting".

> The `title` and `description` keywords must be strings. A "title" will preferably be short, whereas a "description" will provide a more lengthy explanation about the purpose of the data described by the schema.

> The `default` keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, `default` is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of `default` should validate against the schema in which it resides, but that isn't required.

Here's a simple example where this fails:
```python
schema = """{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "test": {
        "type": "integer"
        }
    },
    "required": [
        "test"
    ]
}"""
return generate.json(
    self.model,
    schema,
)(prompt)
```

```bash
File "/usr/local/lib/python3.11/site-packages/outlines/text/generate/regex.py", line 228, in json
regex_str = build_regex_from_schema(schema)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 35, in build_regex_from_schema
schedule = build_schedule_from_schema(schema)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 80, in build_schedule_from_schema
schema = expand_json_schema(schema, definitions)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 134, in expand_json_schema
"title": raw_schema["title"],
~~~~~~~~~~^^^^^^^^^
KeyError: 'title'
null
```

It's very common to have un-titled JSON schemas. As a result, I believe this should not be required. In addition, I think the `title` property may be unused.

**Comment by brandonwillard** [comment]
Just so you know, we've been building the JSON support around basic `pydantic` schemas, so that can explain some of the current limitations with generic JSON schemas.

We definitely plan to expand this into the more general coverage implied here, so many thanks for addressing this issue!  Also, don't hesitate to create a PR with any fixes you might be using locally.  It's fine if the PR is just a draft.

**Comment by mattkindy** [comment]
> We definitely plan to expand this into the more general coverage implied by this issue, so many thanks for opening it! Also, don't hesitate to create a PR with any fixes you might be using locally. It's fine if the PR is just a draft.

I'm definitely considering this -- there are a couple other cases (e.g. [tuples](https://json-schema.org/understanding-json-schema/reference/array#tupleValidation)) that are lacking for my specific use.

**Comment by mattkindy** [comment]
For the moment, if someone needs a workaround for this, I threw this together locally. No guarantees --
```python
parsed_schema = json.loads(schema)

def add_titles(schema_object, title="root"):
    if not isinstance(schema_object, dict):
        return
    if "title" not in schema_object:
        schema_object["title"] = title
    def patch_dict(key):
        if key not in schema_object:
            return
        for inner_key in schema_object[key].keys():
            print(f"Adding title {inner_key} to {key}.{inner_key}")
            add_titles(schema_object[key][inner_key], title=inner_key)
    def patch_array(key):
        if key not in schema_object:
            return
        for i, value in enumerate(schema_object[key]):
            print(f"Adding title {i} to {key}.{i}")
            add_titles(value, title=str(i))
    patch_dict("properties")
    for key in ["anyOf", "oneOf", "allOf"]:
        patch_array(key)
        
add_titles(parsed_schema)

schema = json.dumps(parsed_schema)
```
