### ISSUE TITLE
JSON schema parsing doesn't handle `$ref` properly

### ISSUE THREAD

**Issue by mattkindy** [outlines-dev/outlines#310]
In [outlines/text/json_schema.py#expand_json_schema](https://github.com/outlines-dev/outlines/blob/main/outlines/text/json_schema.py#L95), during the regex generation process, when a `$ref` is encountered in a JSON schema,

https://github.com/outlines-dev/outlines/blob/5af26cb93905605451ffe3a2594a7c60316a7505/outlines/text/json_schema.py#L120

the `definitions` (corresponding to `$def`) object is searched:

https://github.com/outlines-dev/outlines/blob/5af26cb93905605451ffe3a2594a7c60316a7505/outlines/text/json_schema.py#L122

While `$def` <-> `$ref` correspondence is a reasonable practice, this doesn't support a number of other ways in which [$ref](https://json-schema.org/understanding-json-schema/structuring#dollarref) is used. Among other things, this prevents use of `$ref`s like `#/properties/myEquivalentProperty` (which is generated by tools like `zod`'s `zodToJsonSchema` when reusing a schema definition) or [recursive refs](https://json-schema.org/understanding-json-schema/structuring#recursion).

Here's an example where this fails:
```python
schema = """{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "test": {
          "type": "integer"
        },
        "test2": {
          "$ref": "#/properties/test"
        }
    }
}"""
return generate.json(
    self.model,
    schema,
)(prompt)
```

```bash
File "/usr/local/lib/python3.11/site-packages/outlines/text/generate/regex.py", line 228, in json
regex_str = build_regex_from_schema(schema)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 35, in build_regex_from_schema
schedule = build_schedule_from_schema(schema)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 80, in build_schedule_from_schema
schema = expand_json_schema(schema, definitions)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/outlines/text/json_schema.py", line 120, in expand_json_schema
definitions[value["$ref"]], definitions
~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '#/properties/test'
null
```

**Comment by brandonwillard** [comment]
My response here is also relevant, so I'm linking here as well: https://github.com/outlines-dev/outlines/issues/309#issuecomment-1743332075.
