### ISSUE TITLE
Vectorised OpenAI API calls not working

### ISSUE THREAD

**Issue by harshkumarchourasia** [outlines-dev/outlines#365]
### Describe the issue as clearly as possible:

Example in this tweet is not working. 
https://twitter.com/remilouf/status/1724107879941120145

### Steps/code to reproduce the bug:

```python
from outlines import models
model = models.openai("text-davinci-003")
```

### Expected result:

```shell
No expected output
```

### Error message:

<img width="648" alt="image" src="https://github.com/outlines-dev/outlines/assets/58362904/46874827-8841-4b2c-a7de-9ab471caf6b9">

### Outlines/Python version information:

```python
outlines==0.0.9
python==3.11.5
```

**Comment by rlouf** [comment]
Try with outlines v0.0.10, it should work

**Comment by harshkumarchourasia** [comment]
`ERROR: Could not find a version that satisfies the requirement outlines==0.0.10 (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.dev0)
ERROR: No matching distribution found for outlines==0.0.10`
pip version 23.3.1

**Comment by rlouf** [comment]
The `Release` action failed in CI, I will fix this and report back.

**Comment by rlouf** [comment]
V0.0.11 is out, you can give it a try

**Comment by harshkumarchourasia** [comment]
Working now, thanks!
