### ISSUE TITLE
Return the number of prompt and generated tokens for API providers

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#387]
The number of prompt and generated tokens is important to evaluate the cost of each query. I suggest to return a class that contains the generation as well as these numbers.

**Comment by HerrIvan** [comment]
I suppose the goal is keeping the counts of the tokens consumed for each instance of the OpenAI, right? Maybe keeping last and accumulated tokens, s.t. whoever is interested can inspect these values after each call.

**Comment by rlouf** [comment]
I was thinking about returning it at every step, but keeping it as a class attribute is much better!
