### ISSUE TITLE
Restore the ability to stop when a specified string has been generated

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#417]
This was removed in #366 to simplify the PR. It should be simple to implement it at the `SequenceGenerator` level.

**Comment by RobinPicard** [comment]
I see how we could check whether all sequences contain the stop characters after `last_state = next(states)` in `SequenceGenerator.__call__` but I can't find a way of ending the generation for a particular sequence if this one includes the stop characters (but not the others) without modifying the `sequence_generator` function. Do you have a solution in mind?

**Comment by rlouf** [comment]
Can't we do this at the `SequenceGenerator` level?
