### ISSUE TITLE
Handle `Optional` fields in Pydantic models

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#419]
Outlines does not take the `required` field into account in JSON Schemas.

**Comment by RobinPicard** [comment]
On the more general topic of the translation of a JSON Schema into a regex, do you think it would make sense at some point to create an intermediary representation of the JSON Schema with a custom Python object to facilitate the creation of the regex string afterward?

**Comment by rlouf** [comment]
What would be the benefits?

**Comment by RobinPicard** [comment]
I think the benefit could be a clearer separation between the characters for the actual content of the keys/values, those for the logical operations (caused by required, anyOf...) and those related to the json syntax (the quotation marks, commas...). I imagined it could make it easier to add new features

**Comment by brandonwillard** [comment]
> I think the benefit could be a clearer separation between the characters for the actual content of the keys/values, those for the logical operations (caused by required, anyOf...) and those related to the json syntax (the quotation marks, commas...). I imagined it could make it easier to add new features

This sounds like a broader, speculative design-level implementation consideration.  For this issue, we first need to determine how we might want to implement `Optional` using the current regex approach.  After that, we'll have a better idea of which implementation designs/refactoring/IR will best facilitate this and the existing features.
