### ISSUE TITLE
Inference failed with error Invalid \\escape: line 3 column 373 (char 424)

### ISSUE THREAD

**Issue by MelodiousThonk** [outlines-dev/outlines#432]
### Describe the issue as clearly as possible:

When using Outlines to generate JSON schemas, I get this error approx. %5 of the time: `Invalid \\escape: line 3 column 373 (char 424)` even with very simple schemas: `{prompt: str}` and for the same prompt.

### Steps/code to reproduce the bug:

```python
import outlines


model = outlines.models.transformers("TheBloke/zephyr-7B-beta-GPTQ", device="cuda")
json_schema = json.dumps({
  "type": "object",
  "properties": {
    "poem": {
      "type": "string"
    }
  }
})
generator = outlines.generate.json(model, json_schema)

sequence = generator("Write a long poem")
print(sequence)
```

### Expected result:

```shell
{"poem": "blablabla"}
```

### Error message:

```shell
Invalid \\escape: line 3 column 373 (char 424)
```

### Outlines/Python version information:

```python
outlines==0.0.13
```

### Context for the issue:

The error comes from the JSON library. Our guess is that the string generated through outlines is not accepted by the json library.

**Comment by rlouf** [comment]
Any chance you could use a debugger and output the string that’s generated before parsing?

**Comment by brandonwillard** [comment]
Better yet, could you set the `rng`s and get one to reproduce the issue?

**Comment by rlouf** [comment]
This seems to be an issue with the model exceeding the context length before it has the time to output `}`. Can you try by constraining the length of the string field using `maxLength`?
