### ISSUE TITLE
Support regexs in vLLM

### ISSUE THREAD

**Issue by brandonwillard** [outlines-dev/outlines#478]
### Discussed in https://github.com/outlines-dev/outlines/discussions/474

<div type='discussions-op-text'>

<sup>Originally posted by **mjsteele12** December 22, 2023</sup>
The [JSON implementation](https://outlines-dev.github.io/outlines/reference/vllm/) for vllm API is fantastic! I am opening this discussion to suggest adding regex support since I believe it will be equally useful. IMO one place where local llms really shine is running data ETL/NLP tasks around the clock. This requires guaranteed output structure provided by regex/outlines. For example, something I am working on right now in my RAG pipeline is to add structured/curated metadata derived from text which can be used to drastically reduce the search space. Regex support is crucial for extraction tasks like dates, emails, phone numbers etc. </div>

**Comment by rlouf** [comment]
We can separate the different cases so `outlines.serve.serve` is replaced by `outlines.serve.json` and `outlines.serve.regex`

**Comment by tscholak** [comment]
I can pick this one up. I'm touching this stuff anyway right now

**Comment by rlouf** [comment]
That would be amazing

**Comment by tscholak** [comment]
I updated #481 to also add a `regex_string` field to the request. So I didn’t quite do what you suggested, @rlouf, i.e.

> We can separate the different cases so `outlines.serve.serve` is replaced by `outlines.serve.json` and `outlines.serve.regex`

Instead, the server handles both, but not at the same time.
