### ISSUE TITLE
Cache `RegexFSM`

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#483]
Compilation of FSMs can be quite costly, and at the very least users shouldn't need to re-compile FSMs that have already been compiled. This is why we should cache (on disk), given a regex and a vocabulary, the map from states to tokens created in the `__init__` method of `RegexFSM`.

**Comment by brandonwillard** [comment]
Related to https://github.com/outlines-dev/outlines/issues/339?

**Comment by rlouf** [comment]
Related, but I think the approach proposed here is different by caching the result of the entire FSM/index building process, without needing to cache the result of intermediate functions directly. Is there something I'm missing?

**Comment by GastonRAraujo** [comment]
is this the reason that i got very long times to get the generator when passing maxLenght to a schema?
