### ISSUE TITLE
Include traditional language model inference endpoints in server

### ISSUE THREAD

**Issue by wdhitchc** [outlines-dev/outlines#485]
### What behavior of the library made you think about the improvement?

Currently, we only have Guided generation as an endpoint in the server. This is not ideal as I need a separate inference server with basic completions.

### How would you like it to behave?

I would like to be able to pass no JSON structure or guidance to the generate function. I should also have control over several things like temperature, stop tokens etc. I honestly believe we could copy code directly from the VLLM inference server endpoint. Ideally we could use the Open AI compliant server if we wanted.

**Comment by rlouf** [comment]
Have you tried no passing `schema` to the API? It should default to just generating text. Also we copied the code from vLLM so you should be able to pass any argument you can pass to vLLM.

**Comment by wdhitchc** [comment]
Great, I haven't actually tried but given this is the case I'll go ahead and get this deployed asap, because this is awesome! Great work to this team

**Comment by rlouf** [comment]
I'll close this for now, reopen if it doesn't work for some reason.
