### ISSUE TITLE
llama.cpp with outlines

### ISSUE THREAD

**Issue by andysingal** [outlines-dev/outlines#493]
Would be nice to have llama.cpp compatible with outlines, running a mixtral, mistral, notux makes you run out of memory.
Regards,
Andy

**Comment by rlouf** [comment]
See #486 :)

**Comment by andysingal** [comment]
> See #486 :)

i was trying something

> See #486 :)

any doc link?

**Comment by rlouf** [comment]
It's being implemented

**Comment by andysingal** [comment]
Link??

**Comment by rlouf** [comment]
It's in my first message.
