### ISSUE TITLE
Add CFG guided generation to vLLM integration 

### ISSUE THREAD

**Issue by lapp0** [outlines-dev/outlines#494]
Similar to https://github.com/outlines-dev/outlines/issues/478

Great to see regex for vLLM, would love to see grammars as demonstrated in the readme in the section https://github.com/outlines-dev/outlines/tree/0355ab4272a5d7e4d94c4a53a52593f885b81a61#using-context-free-grammars-to-guide-generation used with vLLM!

**Comment by mory91** [comment]
Hi,
I've implemented this in #517
