### ISSUE TITLE
Install Pydantic>=2.0 after vLLM installation

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#504]
Outlines and vLLM currently clash because installing vLLM after outlines downgrades to Pydantic<2. Either we can dictate the order in which packages are installed, or we document the fact that we need to run `pip install pydantic>=2`

**Comment by chrispr8** [comment]
I think this should get fixed on this side: https://github.com/vllm-project/vllm/issues/1396

**Comment by rlouf** [comment]
There is a [PR open](https://github.com/vllm-project/vllm/pull/2468) on vLLM to bump the version. In the meantime I updated the documentation in #547.

**Comment by chrispr8** [comment]
The issue got fixed in the vLLM-repo. Until they release v0.2.8 you can use

> pip install git+https://github.com/vllm-project/vllm

to install the current main branch.

**Comment by rlouf** [comment]
Have you tried it?

**Comment by viktor-ferenczi** [comment]
With the current doc this was needed: `pip install diskcache`

But `pip install pydantic>=2` was unnecessary.
