### ISSUE TITLE
Add module with grammars

### ISSUE THREAD

**Issue by rlouf** [outlines-dev/outlines#543]
A user interface to grammar guided generation was recently added to the repository, but grammars can be hard to craft. I propose that we add a module in outlines that contains grammars that are ready to use, as was suggested several times.

Using a grammar would look like:

```python 
import outlines

sql_grammar = outlines.grammars.sql
```

An alternative, which was the original plan, is to have a separate library that contains grammars. We might follow this route down the line, if it turns out there's a larger audience for them. But for now it is more cumbersome for users.

**Comment by viktor-ferenczi** [comment]
We have multiple SQL dialects, but adding a few common ones makes sense. Like full grammar for SQLite, PostgreSQL and MSSQL SELECT syntax would be used very commonly, I guess.

Another examples would be approximate (non-validating) grammars for the most common programming languages. It could potentially save a lot of retries with small code generation models especially when they are running quantized and prone to put random characters breaking syntax here and there.

**Comment by lapp0** [comment]
That's a great idea and would lower the barrier to entry.

Here's larks official repo: https://github.com/ligurio/lark-grammars/tree/master/lark_grammars/grammars

Small note: We would need to source a modified `common.lark` which has a regular definition for `ESCAPED_STRING` since larks definition is non-regular and cannot be interpreted by `interegular`: 

https://github.com/lark-parser/lark/blob/262ab71d497a8814f0ca42ca468b923fdb47a3c7/lark/grammars/common.lark#L27

```
_STRING_ESC_INNER: _STRING_INNER /(?<!\\)(\\\\)*?/

ESCAPED_STRING : "\"" _STRING_ESC_INNER "\""
```

**Comment by rlouf** [comment]
[This repository](https://github.com/ligurio/lark-grammars/tree/master) contains a bunch of Lark grammar, with a permissive licence, but looks unmaintained. We would need to ask the owner of the repository first, and be careful with licence and attribution.

**Comment by viktor-ferenczi** [comment]
> [This repository](https://github.com/ligurio/lark-grammars/tree/master) contains a bunch of Lark grammar, with a permissive licence, but looks unmaintained. We would need to ask the owner of the repository first, and be careful with licence and attribution.

That repository has the [ISC License](https://en.wikipedia.org/wiki/ISC_license).

"It is functionally equivalent to the simplified BSD and MIT licenses, but without language deemed unnecessary"

**Comment by lapp0** [comment]
Hi @amoffat

I reviewed the SQL select statement lark files you wrote in these three files. They're easily the most comprehensive and well written I've found on GitHub!

- https://github.com/amoffat/HeimdaLLM/blob/dev/heimdallm/bifrosts/sql/mysql/select/grammar.lark
- https://github.com/amoffat/HeimdaLLM/blob/dev/heimdallm/bifrosts/sql/postgres/select/grammar.lark
- https://github.com/amoffat/HeimdaLLM/blob/dev/heimdallm/bifrosts/sql/sqlite/select/grammar.lark

The AGPL license of HeimdaLLM is incompatible with Outlines' Apache 2 license. Would you be willing to allow us to use your grammars in Outlines under the Apache 2 license so users of Outlines can benefit from them as well?

Thanks,
Andrew Lapp

**Comment by amoffat** [comment]
Hi :wave:

I can only offer the AGPL or the commercial license for HeimdaLLM IP at this time, so I must decline the request to re-license those files. FWIW, those grammars are very (intentionally) limited and integrate tightly with the HeimdaLLM parser logic, so I think they would not be as useful as you would need.

Also, big fan of outlines. You all are doing very cool stuff :+1:

**Comment by lapp0** [comment]
Thanks for your consideration regardless @amoffat!
