### ISSUE TITLE
Way to sponsor the project

### ISSUE THREAD

**Issue by viktor-ferenczi** [outlines-dev/outlines#551]
### What behavior of the library made you think about the improvement?

No sponsorship link provided.

### How would you like it to behave?

Please add a way to sponsor the project. A PayPal link would do, for example.

My work depends on getting the constrained generation working well with vLLM. This includes tensor parallel mode, JSON, regex and Lark grammar. Today I got it working (except of the Lark grammar) by cherry-picking changes from PRs and making a fix myself. So it is coming together nicely and I would like to keep the project going.

Thanks.

**Comment by SupreethRao99** [comment]
@viktor-ferenczi could you tell us more about how you got contained generation working with tensor parallel mode? a lot of my work also involves a lot of constrained generation.

Thanks!

**Comment by viktor-ferenczi** [comment]
@rlouf Could you please review this? Thanks!

**Comment by viktor-ferenczi** [comment]
Take a look into this ticket: #524

Found a solution in `lapp0`'s PR: #539

[Fixed the problem](https://github.com/outlines-dev/outlines/issues/524#issuecomment-1896274756) with that PR, so it works now. Waiting on the PR's author (lapp0) to take the fix and get his PR reviewed.

Until then I keep a working `outlines` branch here: https://github.com/viktor-ferenczi/outlines/tree/dev

Please note, that my branch includes code from my open PR to change the vLLM request parameters, but you can cherry-pick only the fix to the `RegexLogitsProcessor`, that's a separate commit.

**Comment by rlouf** [comment]
@viktor-ferenczi Thank you so much, it means a lot to us that you're appreciating our work! No need for sponsorship, but we're thinking about ways to get the community more involved in our journey.

**Comment by simon-mo** [comment]
From vLLM perspective, we are big fan of Outlines! From our side, we will make sure this is also a priority, please don't hesitate to reach out and let us know what's the blocker.
