### ISSUE TITLE
llamacpp (gguf) generation looks "wrong"

### ISSUE THREAD

**Issue by msjgriffiths** [outlines-dev/outlines#553]
I get different (worse) results when loading a `gguf` model via `llamacpp` than if I use `llamacpp` directly.

For example:

```python
from outlines import models, generate
from llama_cpp import Llama

file = "phi-2.Q2_K.gguf"
# Llamacpp via Python bindings
llm = Llama(model_path=file)

# Outlines
model = models.llamacpp(file)
outlines_llm = generate.text(model)

llm("""Instruct: Write a detailed analogy between mathematics and a lighthouse.\nOutput:""", max_tokens=20)['choices'][0]['text']
#> Mathematics is like a lighthouse in the sense that it provides guidance and direction to those who seek knowledge, 


outlines_llm("""Instruct: Write a detailed analogy between mathematics and a lighthouse.\nOutput:""", 20)
#>        Although its purpose is unrelated, a lighthouse and Mathematics could be compared to'       Although its purpose is unrelated, a lighthouse and Mathematics could be compared to'
```

That makes it hard to use `outlines` for interfacing with `llamacpp`. Plausible that #540 could help address this.

**Comment by rlouf** [comment]
@dtiarks will soon start working on this and it should definitely help

**Comment by dtiarks** [comment]
The outlines result definitely looks wrong! But just to make this clear: is the repetition in the outlines result an artifact of your copy & pasting or was it actually generated by outlines?

When running your code locally I don't see any repetition and my result looks legit (although different, but this is probably due to different sampling strategies).

**Comment by msjgriffiths** [comment]
I'll check again. I believe it was produced by outlines but would be happy to be wrong 

Good to hear it works on your machine. I'm on a M1 Mac - don't know if that's different - or if there's some other issue. I am operating in a virtual environment I made just with outlines.

**Comment by dtiarks** [comment]
Ok. In general it's expected that there's a difference between the two. Mainly due to different sampling strategies.
