### ISSUE TITLE
Official Docker Builds

### ISSUE THREAD

**Issue by lapp0** [outlines-dev/outlines#555]
### What behavior of the library made you think about the improvement?

Users, including me, have their own bespoke Docker containers and build workflows. There are a few unofficial images on the hub https://hub.docker.com/search?q=outlines&sort=updated_at&order=desc&type=image

### How would you like it to behave?

Users should use a trusted official image. This will allow quick integration of Outlines into their project.

A new image should be built with every merge via CI.

**Comment by rlouf** [comment]
Do you have examples of libraries providing a Docker image?

**Comment by lapp0** [comment]
Yes, this is specifically for vLLM serving.

example with vLLM:
- https://github.com/vllm-project/vllm/blob/main/Dockerfile
- https://hub.docker.com/r/vllm/vllm-openai

I think it would be great if users could get up and running immediately with outlines + vLLM through an official Docker image.

**Comment by rlouf** [comment]
I think we should hold off for now, and see what happens on the vLLM side. It's fine if users create their own Docker image, but adding one in the repo adds maintenance overhead.

**Comment by rlouf** [comment]
Re-opening this, I am open to adding an official Docker build. We can start with adding a Dockerfile and take it from there.
