### ISSUE TITLE
Cache Can Break on Version Update

### ISSUE THREAD

**Issue by lapp0** [outlines-dev/outlines#561]
### Describe the issue as clearly as possible:
https://github.com/outlines-dev/outlines/pull/544 doesn't work for me unless I delete the cache introduced in https://github.com/outlines-dev/outlines/pull/492

This is because a cached functions signature has changed, resulting in this error:

```
>       self.states_to_token_maps, self.empty_token_ids = create_states_mapping(
            regex_string, tuple(sorted(tokenizer.vocabulary.items()))
        )
E       ValueError: too many values to unpack (expected 2)
```

We should either incorporate a version number into the cache or clear the cache upon user upgrade.

### Reproduction steps
- checkout main
- construct a `RegexFSM`
- checkout https://github.com/outlines-dev/outlines/pull/544
- construct the same `RegexFSM`

**Comment by rlouf** [comment]
How do libraries usually do this?

**Comment by lapp0** [comment]
I can't find much prior art. I recommend we do something like

```
memory = Cache(cache_dir, eviction_policy="none", cull_limit=0)
if "__version__" in memory and outlines.__version__ != memory["__version__"]:
    memory.clear()
memory["__version__"] = outlines.__version__
```

We would then require anyone writing breaking changes to a cached function to increment Outlines patch number.
