### ISSUE TITLE
Enable `%ignore` directives

### ISSUE THREAD

**Issue by lapp0** [outlines-dev/outlines#565]
### What behavior of the library made you think about the improvement?

https://github.com/outlines-dev/outlines/blob/6c6966cfa24e9c120494ebb317c6126aa2ae94af/outlines/fsm/parsing.py#L105

`%ignore` doesn't work. For example in the below grammar `WS` wouldn't be generated at any point.

```
?start: value

?value: object
| array
| UNESCAPED_STRING
| SIGNED_NUMBER      -> number
| "true"             -> true
| "false"            -> false
| "null"             -> null

array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)*] "}"
pair   : UNESCAPED_STRING ":" value

%import common.UNESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS

%ignore WS
```

### How would you like it to behave?

If the `%ignore` directive is included, the ignored terminal it should be allowed as the next terminal at any point in generation. (Use of the ignored terminal doesn't modify the pushdown automaton)

**Comment by lapp0** [comment]
@brandonwillard before I blindly walk into this, could you give me some insights into why we disabled ignored terminals and what issues I might run into?

https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L101

https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L375

https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L691

https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L749

**Comment by brandonwillard** [comment]
> @brandonwillard before I blindly walk into this, could you give me some insights into why we disabled ignored terminals and what issues I might run into?
> 
> https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L101
> 
> https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L375
> 
> https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L691
> 
> https://github.com/outlines-dev/outlines/blob/950a5c128013dcd3ab528ce4924250c4ecbd1b8f/outlines/fsm/parsing.py#L749

Ignored tokens aren't processed by the parser&mdash;by definition&mdash;and most/all of those links reflect that aspect of the parsing logic.

**Comment by lapp0** [comment]
Thanks, makes sense. I'll work on a changeset which ensures the parser isn't impacted my them, but the lexer can consume them and `RegexFSM` is constructed.
