### ISSUE TITLE
`generate.format` returns a string instead of the corresponding type

### ISSUE THREAD

**Issue by dnhkng** [outlines-dev/outlines#589]
### Describe the issue as clearly as possible:

I think the example code is broken in syntax, and also the results are not correctly working.

### Steps/code to reproduce the bug:

```python
import outlines

model = outlines.models.transformers("mistralai/Mistral-7B-v0.1")

prompt = "1+1="
answer = outlines.generate.format(model, int)(prompt)

prompt = "sqrt(2)="

generator = outlines.generate.format(model, float)
answer = generator(prompt)

print(answer)
print(type(answer))
```

### Expected result:

```shell
1.414
float
```

### Error message:

```shell
1.414
str
```

### Outlines/Python version information:

0.0.25.dev15+g0cd9608
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

### Context for the issue:

Firstly, I think the example code is wrong:
```
prompt = "1+1="
answer = outlines.generate.format(model, int)(prompt)

prompt = "sqrt(2)="

generator = outlines.generate.format(model, float)
answer = generator(prompt)
```

I assume it should be:
```
prompt = "1+1="
generator = outlines.generate.format(model, int)(
answer = generator(prompt)

prompt = "sqrt(2)="

generator = outlines.generate.format(model, float)
answer = generator(prompt)
```

Secondly, for both inferences, 'answer' is a string, not an int or float.

Lastly, I also tried the "Efficient JSON generation following a Pydantic model" example, and was returned a python object. Should this directly be a json string? it's not clear.

**Comment by lapp0** [comment]
I agree, it does seem reasonable for the format function to return the object itself. Of course, we should avoid using eval(), so there's a need for a function that converts strings to objects, in line with the definitions provided in the module below that defines each types regex:

https://github.com/outlines-dev/outlines/blob/main/outlines/fsm/types.py

**Comment by dnhkng** [comment]
A case of "The Principle of Least Astonishment" :)

**Comment by rlouf** [comment]
I agree we should change the interface. `SequenceGenerator` has a method that post-processes the generated string so that would be the way to go about it.

Thank you for pointing this out!
