### ISSUE TITLE
Output probabilities

### ISSUE THREAD

**Issue by dnhkng** [outlines-dev/outlines#591]
The library [CAPPR](https://cappr.readthedocs.io/en/latest/) allows the probabilities for each completion to be calculated. Although these are not usable as a measure of certainty in LLMs, I have a strong need to get access to them.

Currently, we can use this code to get categorical answers:
```
import outlines

model = outlines.models.transformers("mistralai/Mistral-7B-v0.1")

prompt = """You are a sentiment-labelling assistant.
Is the following review positive or negative?

Review: This restaurant is just awesome!
"""

generator = outlines.generate.choice(model, ["Positive", "Negative"])
answer = generator(prompt)

print(answer) # Positive
```

I want this "probability" method:
```
import outlines

model = outlines.models.transformers("mistralai/Mistral-7B-v0.1")

prompt = """You are a sentiment-labelling assistant.
Is the following review positive or negative?

Review: This restaurant is just awesome!
"""

generator = outlines.generate.probability(model, ["Positive", "Negative"])
answer = generator(prompt)

print(answer) # [0.8. 0.2]
```

**Comment by rlouf** [comment]
Possible duplicate of #479

**Comment by dnhkng** [comment]
@rlouf Point me to the right place in the code, and I'll try to implement it.

**Comment by dnhkng** [comment]
Yes, its a dupe, but rather than modifying "choice", I would like a new method. But I'll close this issue.

**Comment by dnhkng** [comment]
Yes, its a dupe, but rather than modifying "choice", I would like a new method. But I'll close this issue.
