### ISSUE TITLE
Issues with CUDA and the examples in the tutorial 

### ISSUE THREAD

**Issue by raphaelchinchilla** [outlines-dev/outlines#656]
### Describe the issue as clearly as possible:

I am trying to get outlines to work on CUDA. 

I just modified the example in the README to force the model to go to CUDA (otherwise it would go to the CPU).

However, I get an error. It seems that the tokenizer is not sending the prompt to the CUDA.

### Steps/code to reproduce the bug:

```python
from enum import Enum
from pydantic import BaseModel, constr

import outlines
import torch


class Weapon(str, Enum):
    sword = "sword"
    axe = "axe"
    mace = "mace"
    spear = "spear"
    bow = "bow"
    crossbow = "crossbow"


class Armor(str, Enum):
    leather = "leather"
    chainmail = "chainmail"
    plate = "plate"


class Character(BaseModel):
    name: constr(max_length=10)
    age: int
    armor: Armor
    weapon: Weapon
    strength: int


model = outlines.models.transformers("mistralai/Mistral-7B-Instruct-v0.2",device="cuda")

# Construct structured sequence generator
generator = outlines.generate.json(model, Character)

# Draw a sample
rng = torch.Generator(device="cuda")
rng.manual_seed(789001)

character = generator("Give me a character description", rng=rng)

print(repr(character))
# Character(name='Anderson', age=28, armor=<Armor.chainmail: 'chainmail'>, weapon=<Weapon.sword: 'sword'>, strength=8)

character = generator("Give me an interesting character description", rng=rng)

print(repr(character))
# Character(name='Vivian Thr', age=44, armor=<Armor.plate: 'plate'>, weapon=<Weapon.crossbow: 'crossbow'>, strength=125)
```

### Expected result:

```shell
The one on the README
```

### Error message:

```shell
On line 198 of outlines/generate/generator.py

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cudo:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by rlouf** [comment]
I just released `0.0.30`, could you update and try again ?

**Comment by raphaelchinchilla** [comment]
It now works with device="cuda" but does not work with device="auto". The error I get is

On line 198 of outlines/generate/generator.py

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by rlouf** [comment]
It's basically saying that `kv_cache` and `ancestors` are not on the same device. A simple fix would be to use `ancestors.to(layer.device)ˋ.

**Comment by rlouf** [comment]
Could you confirm #660 solved your problem?

**Comment by raphaelchinchilla** [comment]
Just tested, and it works on several examples!

Thanks so much (also, sorry for the delay, time zone difference)

Would you release a new version at some point so I can use the pypi one instead of my local?
