### ISSUE TITLE
Update readme link to grammars

### ISSUE THREAD

**Issue by thekevinscott** [outlines-dev/outlines#663]
### What behavior of the library made you think about the improvement?

[The readme section on grammars reads](https://github.com/outlines-dev/outlines?tab=readme-ov-file#using-context-free-grammars-to-guide-generation):

> All you have to do is search for "X EBNF grammar" on the web, and take a look at the [Outlines Grammars repository](https://github.com/outlines-dev/grammars).

The link does not work.

### How would you like it to behave?

I would like the link to point to a Github repo where I can learn more.

**Comment by lapp0** [comment]
Thanks for pointing this out.

Grammar files now reside in https://github.com/outlines-dev/outlines/tree/main/outlines/grammars

There are a few more being introduced here if you're curious https://github.com/lapp0/outlines/tree/benchmark-cfg-generation/outlines/grammars

**Comment by thekevinscott** [comment]
Fantastic, thank you!
