### ISSUE TITLE
Feature Matrix

### ISSUE THREAD

**Issue by lapp0** [outlines-dev/outlines#675]
### What behavior of the library made you think about the improvement?

It's not obvious which features are compatible with each model. A user was recently struggling with running a quantized model on CPU with Outlines.

### How would you like it to behave?

Create a table showing for each model whether a feature can be used.

Rows: models

Columns: Samplers (e.g. only multinomial with llamacpp), constrained generation (e.g. no json with openai), GPU / CPU (some models support both, some models only support one)

Labels: 
- supported: ✅, 
- WIP or planned: 🔨
- impossible or no plans: ❌

**Comment by lapp0** [comment]
|                            | Transformers | vLLM | llama.cpp | ExLlamaV2 | Mamba | OpenAI |
|----------------------------|--------------|------|-----------|-----------|-------|--------|
| **Sampling**               |              |      |           |           |       |        |
| Greedy                     | ✅           | ✅   | X         | ✅        | ✅    | ❌     |
| Multinomial                | ✅           | ✅   | ✅        | ✅        | ✅    | ✅     |
| Beam Search                | ✅           | ✅   | X         | ✅        | ✅    | ❌     |
| **Generation**             |              |      |           |           |       |        |
| Text                       | ✅           | ✅   | ✅        | ✅        | ✅    | ✅     |
| Constrained                | ✅           | ✅   | ✅        | ✅        | ✅    | ❌     |
| **Device**                 |              |      |           |           |       |        |
| CPU                        | ✅           | ❌   | ✅        | ✅        | ❌    | N/A    |
| Cuda                       | ✅           | ✅   | ✅        | ✅        | ✅    | N/A    |

**Comment by rlouf** [comment]
> Might be able to add Beam Search and Greedy to llama.cpp, I'll look into whether it's possible and create an issue if so.

You can do greedy by setting temperature to 0, but I don't think there is a wrapper for beam search yet.
