### ISSUE TITLE
llamacpp: Controlled generation overwrites model instance

### ISSUE THREAD

**Issue by msjgriffiths** [outlines-dev/outlines#700]
I would expect to use a single model to do different controlled generation tasks. However, when I create different controlled generation functions, I find that the underlying model object is over-ridden -- letting only the latest one work. 

For example, in a new environment:

```sh
conda create -n "outlines-llamacpp" python=3.10 
conda activate outlines-llamacpp
pip install outlines llama-cpp-python ipython
```

This installs `outlines-0.0.32`.

Let's try to make two "choosing" features, one for numbers and one for cities.

```python
import transformers
from outlines import models, generate

path = "gemma-2b-it-q4_k_m.gguf"
model = models.llamacpp(
  path, 
  model_kwargs={
   'n_ctx': 8000,
   'n_gpu_layers': 32
  }
)

choose = generate.regex(model, r"(one|two|three)")
choose("pick a numner")
# 'one'

cities = generate.choice(model, ["New York", "Paris", "San Francisco"])
cities("pick a city")
#  'San Francisco'

choose("a number")
# 'New York'
```

The last outcome is **unexpected**, because I would expect that to be constrained to a number.

Additionally, I cannot "reset" it with just text, e.g. 

```python
text = generate.text(model)
text("tell me a joke")

# 'San Francisco'
```

The only way I can control this is by manually swapping out the `logits_processor` attribute of the model instance, e.g. this works:

```python
choose = generate.regex(model, r"(one|two|three)")
choose("pick a numner")
# 'one'

# Keep pointer
chooser = model.logits_processor

cities = generate.choice(model, ["New York", "Paris", "San Francisco"])
cities("pick a city")
#  'San Francisco'

choose("a number")
# 'New York'

model.logits_processor = chooser
choose("a number")
# 'one'

```

**Comment by rlouf** [comment]
I just pushed a fix, checked that it works on your example. Will cut a new release shortly.

**Comment by msjgriffiths** [comment]
Wow, that was fast. Thank you!
