### ISSUE TITLE
Docs for initializing from LlamaCpp incorrect

### ISSUE THREAD

**Issue by ahuang11** [outlines-dev/outlines#730]
https://outlines-dev.github.io/outlines/reference/models/llamacpp/

```
from llama_cpp import Llama
from outlines import models

llm = Llama.from_pretrained(
    repo_id="Qwen/Qwen1.5-0.5B-Chat-GGUF",
    filename="*q8_0.gguf",
    verbose=False
)
model = models.LlamaCpp(llm)
```

`TypeError: stat: path should be string, bytes, os.PathLike or integer, not Llama`

from 
```
 LlamaCpp.__init__(self, model_path, **kwargs)
     90 def __init__(self, model_path, **kwargs):
     91     from llama_cpp import Llama
---> 93     self.model = Llama(model_path, **kwargs)
     94     self.tokenizer = LlamaCppTokenizer(self)
```

### How would you like it to behave?

To initialize from Llama

**Comment by rlouf** [comment]
Yes sorry, a change was pushed to `main` yesterday that updated the docs as well. In the released version one can only initialise a model as follows:

```python
from outlines import models

llm = models.llamacpp("path_to_my_model")
```

I will cut a new release later today and the documentation should then be accurate.
