### ISSUE TITLE
Improve index construction performance with bitmaps

### ISSUE THREAD

**Issue by brandonwillard** [outlines-dev/outlines#758]
### What behavior of the library made you think about the improvement?

One of the internal improvements we have at [.txt](https://dottxt.co/) involves a significantly more efficient representation of the vocabulary subsets stored in the index.  By replacing the use of standard `set`s with something like https://pypi.python.org/pypi/roaringbitmap, `outlines` could have the same improvements.

**Comment by lapp0** [comment]
I think this issue should be closed. 

The vocabulary subsets are now indexed as `torch.Tensor`, which allows for runtime performance 50x faster than indexing as `List[int]` https://github.com/outlines-dev/outlines/pull/1013

If the vocabulary subsets were indexed as any other type, an intermediary step would be necessary to convert to `torch.Tensor` for mask construction.

Please re-open if you disagree.
