### ISSUE TITLE
JSON Integers cannot be negative?

### ISSUE THREAD

**Issue by posionus** [outlines-dev/outlines#776]
Hello,
I'm wondering if there is a particular reason why it seems JSON integers cannot be negative.

See:
https://github.com/outlines-dev/outlines/blob/aed9d21bb622e3579c3296a73a0240e36d04180d/outlines/fsm/json_schema.py#L14

"No negatives" seems to be explicitly tested for:
https://github.com/outlines-dev/outlines/blob/aed9d21bb622e3579c3296a73a0240e36d04180d/tests/fsm/test_json_schema.py#L65

This seems incorrect to me, but maybe I'm missing something.

**Comment by rlouf** [comment]
This is indeed wrong. Would you be willing to submit a PR?
