### ISSUE TITLE
Gemini Compatibility with Outlines

### ISSUE THREAD

**Issue by CD-rajveer** [outlines-dev/outlines#792]
Is gemini compitable with outlines. if not then this integration is very useful.

**Comment by rlouf** [comment]
What would you like to do with Outlines that you can't do with the API already?

**Comment by brandonwillard** [comment]
Yes, `outlines` works with Gemini; see [our blog post](https://blog.dottxt.co/how-fast-cfg.html) for an example.

**Comment by brandonwillard** [comment]
Sorry, misread that!  Reopening.

**Comment by CD-rajveer** [comment]
@rlouf is right, Gemini is capable of doing anything if given right set of instructions. need to focus on prompt engineering for gemini
