### ISSUE TITLE
"additionalProperties" should not be a required field

### ISSUE THREAD

**Issue by sgsdxzy** [outlines-dev/outlines#844]
### Describe the issue as clearly as possible:

Currently for object, `"additionalProperties"` is required to be a dict. However, it can be optional or `false`.

### Steps/code to reproduce the bug:

A simple schema, sent to vLLM/Aphrodite-engine as `guided_json`. The properties and types of `parameters` cannot be known beforehand because the function signature varies for different tools. This schema works fine in `lm-format-enforcer`

```python
json_template = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "tool_name": {"type": "string"},
            "parameters": {"type": "object"},
        },
        "required": ["tool_name", "parameters"],
    },
    "minItems": 1,
    "maxItems": 1,
}
```

### Expected result:

```shell
[
    {
        "tool_name": "internet_search",
        "parameters": {
            "query": "biggest penguin species",
            "provider": "Google"
        }
    }
]
```

### Error message:

```shell
ERROR:      File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/modeling/guided_decoding/outlines_decoding.py", line 126, in _get_cached_logits_processor
ERROR:        return JSONLogitsProcessor(guide, tokenizer)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/sgsdxzy/Programs/aphrodite-engine/aphrodite/modeling/guided_decoding/outlines_logits_processors.py", line 111, in __init__
ERROR:        regex_string = build_regex_from_schema(schema_str, whitespace_pattern)
ERROR:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/sgsdxzy/micromamba/envs/aphrodite/lib/python3.11/site-packages/outlines/fsm/json_schema.py", line 83, in build_regex_from_schema
ERROR:        return to_regex(resolver, content, whitespace_pattern)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/sgsdxzy/micromamba/envs/aphrodite/lib/python3.11/site-packages/outlines/fsm/json_schema.py", line 290, in to_regex
ERROR:        items_regex = to_regex(resolver, instance["items"], whitespace_pattern)
ERROR:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/sgsdxzy/micromamba/envs/aphrodite/lib/python3.11/site-packages/outlines/fsm/json_schema.py", line 142, in to_regex
ERROR:        subregex += to_regex(resolver, value, whitespace_pattern)
ERROR:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/sgsdxzy/micromamba/envs/aphrodite/lib/python3.11/site-packages/outlines/fsm/json_schema.py", line 320, in to_regex
ERROR:        value_pattern = to_regex(
ERROR:                        ^^^^^^^^^
ERROR:      File "/home/sgsdxzy/micromamba/envs/aphrodite/lib/python3.11/site-packages/outlines/fsm/json_schema.py", line 321, in to_regex
ERROR:        resolver, instance["additionalProperties"], whitespace_pattern
ERROR:                  ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:    KeyError: 'additionalProperties'
```

### Outlines/Python version information:

Version information
<details>
```
outlines: 0.0.34
python: 3.11.9
```
</details>

### Context for the issue:

Affects guided json generation for function calling in vLLM/Aphrodite-engine.

**Comment by leloykun** [comment]
@sgsdxzy, the latest version of Outlines uses the `"property"` field if it's present

Updating to `outlines==0.0.41` should fix this issue. Oh, and make sure to install this _after_ installing `vllm`; otherwise, you'll get an error

**Comment by sgsdxzy** [comment]
After upgrading to `outlines==0.0.41`, I am still unable to specify a unconstrained object, for example the following schema:
```
json_template = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "tool_name": {"type": "string"},
            "parameters": {"type": "object"},
        },
        "required": ["tool_name", "parameters"],
    },
    "minItems": 1,
    "maxItems": 1,
}
```
is still rejected by outlines because neither `"properties"` nor `"additionalProperties"` is presented for `"parameters"`, but I want `"parameters"` to be entirely controlled by the llm, as long as it's a valid json object, without any restriction on it's contents. How do I specify a free-form object?

**Comment by lapp0** [comment]
@sgsdxzy Could you please try my branch and report back whether it's working for your use case?

`pip install git+https://github.com/lapp0/outlines@fix-844`

Input script:

```
from outlines.fsm.json_schema import build_regex_from_schema
import json
import re


json_template = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "tool_name": {"type": "string"},
            "parameters": {"type": "object"},
        },
        "required": ["tool_name", "parameters"],
    },
    "minItems": 1,
    "maxItems": 1,
}


pattern = build_regex_from_schema(json.dumps(json_template))


valid_result = """[
    {
        "tool_name": "internet_search",
        "parameters": {
            "query": "biggest penguin species",
            "provider": "Google"
        }
    }
]"""

match = re.match(pattern, valid_result)
assert match.string == valid_result
print("fully matched expectation!")
```

Output:
`fully matched expectation!`

**Comment by sgsdxzy** [comment]
@lapp0 Thanks, I can confirm your branch works correctly.

**Comment by Pavel401** [comment]
I am facing this same issue 
{
    "detail": "500: Error code: 400 - {'error': {'message': \"Invalid schema for response_format 'default': In context=(), 'additionalProperties' is required to be supplied and to be false.\", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}"
}


**Data model**
`from enum import Enum

from pydantic import BaseModel, conint, constr


class SkillCategory(str, Enum):
    sports = "Sports"
    music = "Music"
    other = "Other"


class SkillInto(BaseModel):
    skillName: str
    skillDesc: str
    category: SkillCategory
`

**Code:**

 model = models.openai(
            "gpt-4o-mini",
            api_key=get_env_variable("OpenAI-Key-v2"),
        )
        generator = generate.json(model, SkillInto)
        result = generator(
            "Create a skill template for a new skill "
            + query.skillDescription
            + " with the following details: skillName , skillDescription , category "
        )
        return result

**Comment by DSOTM-RSA** [comment]
I'm getting the same error, also using an Azure OpenAI model **gpt4-o** and the following configs.

` Error code: 400 - {'error': {'message': "Invalid schema for response_format 'default': In context=(), 'additionalProperties' is required to be supplied and to be false.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}`

Substituting for the **phi_model** works fine. Any advice? The api_version for the Open AI model doe match those required for structured generation.

```# Initialize generators
        self.azure_generator = models.azure_openai(
            azure_endpoint=azure_endpoint,
            deployment_name=azure_deployment,
            model_name=azure_deployment,
            api_key=api_key,
            api_version=api_version
        )
        
        self.phi_model = models.transformers("microsoft/Phi-3-mini-4k-instruct")
        
        # Define the workflow step schema
        self.workflow_step_schema = """
        {
            "title": "WorkflowStep",
            "type": "object",
            "properties": {
                "step_number": {"type": "integer"},
                "action": {"type": "string"},
                "expected_outcome": {"type": "string"},
                "time_estimate": {"type": "string"},
                "required_tools": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "escalation_criteria": {
                    "type": ["string", "null"]
                }
            },
            "required": ["step_number", "action", "expected_outcome", "time_estimate", "required_tools"]
        }
        """
        
        # Initialize the JSON generator with the schema
        self.step_generator = generate.json(self.azure_generator, self.workflow_step_schema)`
