### ISSUE TITLE
Unsupported: '^' from integregular when string has pattern in json schema

### ISSUE THREAD

**Issue by ekagra-ranjan** [outlines-dev/outlines#931]
### Describe the issue as clearly as possible:

Hi! When I use json schema in outlines that has regex pattern inside a string type, it tries to run `interegular.parse_pattern(regex_string)` and fails with `Unsupported: '^'`. It happens when regex pattern inside string has `^` or `$`. 

Example json schema
```
{
  "type": "object",
  "properties": {
    "address": {
      "type": "object",
      "properties": {
        "postalCode": {
          "type": "string",
          "pattern": "^\d{5}$"
        }
      }
    }
  }
}
```

This seems like a limitation of interegular but [Outlines supports pattern within string type](https://github.com/outlines-dev/outlines/blob/main/outlines/fsm/json_schema.py#L258) so was wondering if regex pattern in json schema is really supported or not?

Also, it seems we wrap the pattern inside ^ and $ with double quotes. This would convert `^\d{5}$` to `^"\d{5}"$` . We can let the user decide if its string or numbers?

cc: @lapp0 

### Steps/code to reproduce the bug:

```python
import interegular
pattern = "^\d{5}$"
new_pattern = rf'(^"{pattern[1:-1]}"$)' 
print(new_pattern)
regex_pattern = interegular.parse_pattern(new_pattern)
```

### Expected result:

```shell
no error
```

### Error message:

```shell
Unsupported: '^'
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by ekagra-ranjan** [comment]
Hi @brandonwillard @lapp0 can someone confirm this please? Thanks!

**Comment by lapp0** [comment]
Hi @ekagra-ranjan 

Interegular explicitly doesn't support `^` or `$` and has tests asserting this https://github.com/MegaIng/interegular/blob/758f83721c1ac306b96b7a706b69716a67ed954b/tests/test_patterns.py#L83-L84

I'm not sure why outlines converts `^foo$` into `^"foo"$`, this seems to be wrong, they should probably be stripped.

Are you able to make your pattern work by removing the illegal `^` and `$`?

**Comment by ekagra-ranjan** [comment]
> Are you able to make your pattern work by removing the illegal ^ and $?

yes, that works. 

> I'm not sure why outlines converts ^foo$ into ^"foo"$, this seems to be wrong, they should probably be stripped.

this is what confuses me too. I guess this was not intended and should be been stripped as you said
