### ISSUE TITLE
JSON strings cannot generate with "\" character in them

### ISSUE THREAD

**Issue by posionus** [outlines-dev/outlines#935]
### Describe the issue as clearly as possible:

I have fine tuned a model to generate json. I am using outlines with vLLM to force the model to generate correct json schema. Outlines is failing to generate:
```
{
  "cost": null,
  "description": "Net Equity Attributable to Holders of Redeemable Units (\"Net Equity\")",
  "footnotes": [],
  "percent_net_assets": 100.0,
  "value": 3767045854
}
```

Specifically, it is failing to generate the `"(\"Net Equity\")" `in the description field. 

The issue seems to be with this line

https://github.com/outlines-dev/outlines/blob/7723ce8d091230249db8840463c5cdefdb408b8e/outlines/fsm/json_schema.py#L13

It is prohibiting any `\` character inside of the string.

`"Net Equity Attributable to Holders of Redeemable Units (\"Net Equity\")"` is a valid json string. I have tested parsing the json above using python json.loads. It should be able to generate using outlines.

### Steps/code to reproduce the bug:

```python
My schema:

class StatementInvestmentsTotal(BaseModel):
    cost: Optional[float]
    description: Optional[str]
    footnotes: list[str]
    percent_net_assets: Optional[float]
    value: Optional[float]
```

### Expected result:

```shell
Outlines should allow generating backslashes in json strings
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by lapp0** [comment]
Please provide package version info. 

See this thread as well

https://github.com/pytorch/pytorch/issues/21819#issuecomment-2029036618

**Comment by lapp0** [comment]
@posionus any interest in creating a PR for this fix? I have a bit on my backlog.

```
>>> interegular.parse_pattern(json_schema.STRING).to_fsm().accepts(r'"my escaped string: \" okay"')
False

>>> STRING_INNER = r'(?:[^"\\]|\\.)*?'
>>> ESCAPED_STRING = r'"' + STRING_INNER + r'"'
>>> interegular.parse_pattern(ESCAPED_STRING).to_fsm().accepts(r'"my escaped string:  \" okay"')
True
```
