### ISSUE TITLE
Regex decoding speed

### ISSUE THREAD

**Issue by shtoshni** [outlines-dev/outlines#943]
### What behavior of the library made you think about the improvement?

I have been using outlines for input-dependent regex decoding for a structured prediction task. The inputs are in the order of a few thousand tokens, and I use greedy decoding. I have been using v0.39 so far and just upgraded to 0.43. Based on a run over 10 documents, the decoding time has close to doubled (from ~1 hr 30 mins to ~3 hrs).  

### How would you like it to behave?

Faster decoding for input-dependent regex decoding.

**Comment by rlouf** [comment]
Do you know if it's related to compilation or to inference?

**Comment by shtoshni** [comment]
Compilation.

**Comment by brandonwillard** [comment]
It sounds like this issue isn't really about decoding speed.  Without some specifics to reproduce the problem, we can't leave this open, so I'll close this for now.
