### ISSUE TITLE
Using other models than mixtral leads to CUDA error

### ISSUE THREAD

**Issue by liqul** [outlines-dev/outlines#944]
### Describe the issue as clearly as possible:

I have tried using other models such as `NousResearch/Meta-Llama-3-8B-Instruct` and `THUDM/glm-4-9b-chat`. I was using the sample code below:

```python
from outlines import models, generate, samplers
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch 

model_id = "THUDM/glm-4-9b-chat"
if torch.cuda.is_available():
    llm = AutoModelForCausalLM.from_pretrained(model_id, device_map='auto', trust_remote_code=True)
else:
    raise Exception('GPU not available')
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
if tokenizer.pad_token_id is None:
    # Required for batching example
    tokenizer.pad_token_id = tokenizer.eos_token_id
model = models.Transformers(llm, tokenizer)

prompt = """You are a sentiment-labelling assistant.
Is the following review positive or negative?

Review: This restaurant is just awesome!
"""

generator = generate.choice(model, ["Positive", "Negative"])
answer = generator(prompt)
```

Then, it always resulted in the following error:

![image](https://github.com/outlines-dev/outlines/assets/7489260/4ae2839b-a05f-4820-8367-8734c60e9216)

My env:
- Python 3.10
- Cuda 12.2
- Pytorch 2.3  
- transformers 4.41.2

### Steps/code to reproduce the bug:

```python
Detailed in the descriptions.
```

### Expected result:

```shell
Expected to output without any errors.
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by lapp0** [comment]
Please provide package version info. 

See this thread as well, it may be a bad pytorch version.

https://github.com/pytorch/pytorch/issues/21819#issuecomment-2029036618

**Comment by lapp0** [comment]
Please try `CUDA_LAUNCH_BLOCKING=1`.

If that fails try `torch=2.3` or `torch=2.0`.

If that fails, please re-open the issue with details on your environment so I can try reproducing your error.
