### ISSUE TITLE
vLLM requirement to be relaxed

### ISSUE THREAD

**Issue by A-F-V** [outlines-dev/outlines#989]
### What behavior of the library made you think about the improvement?

I am trying to contribute on mac, but I run into the following error when I am setting up my dev environment:
```
pip install -e ".[test]"
pre-commit install

```

```
Collecting vllm (from outlines==0.0.46.dev3+g7d8269f)
  Using cached vllm-0.5.0.post1.tar.gz (743 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
...
      AssertionError: vLLM only supports Linux platform (including WSL).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

This makes it difficult for **Mac** and for **non-WSL** developers to contribute

### How would you like it to behave?

To not complain about vLLM requirements not being met to support Mac or non-WSL Windows development

**Comment by lapp0** [comment]
I'm not sure how this can be accomplished without breaking vLLM tests in CI. 

I think you can just run `pip install -e . --no-deps` then ignore vLLM test failures. 

We could also skip vLLM tests if the hardware is inappropriate like we do with mlxlm here https://github.com/outlines-dev/outlines/blob/main/tests/generate/conftest.py#L6

**Comment by lapp0** [comment]
@A-F-V could you please try this PR's branch and let me know whether it works on your end?

https://github.com/outlines-dev/outlines/pull/1005

It doesn't attempt to install vllm on my end.

**Comment by A-F-V** [comment]
I can confirm this PR did solve my issue, and I was also able to run the pytest suite. Thank you :)
